// ── COLORS ───────────────────────────────────────────────────────────────────
export const C = {
  bg:'#fdf6ee', surface:'#fff9f2', card:'#ffffff', border:'#e8d9c5',
  accent:'#c97b3b', accentL:'#f5e4d0', text:'#2c1a0e', mid:'#6b4c35',
  light:'#9c7a60', hero:'#f7ede0', green:'#4a7a4a', greenBg:'#e8f4e8',
  red:'#c0392b', redBg:'#fdf0ee'
};

// ── TYPES ────────────────────────────────────────────────────────────────────
export interface Story {
  id:string; title:string; author:string; genre:string; lang:string;
  cover:string; grad:string; desc:string; tags:string[]; lateNight:boolean;
  chapters:number; views?:number; reads?:string; authorId?:string; body?:string;
}
export interface Wound {
  id:string; quote:string; book:string; author:string;
  date:string; others:number; grad:string;
}
export interface DriftEntry {
  id:string; book:string; state:string; letter:string; date:string; shared:boolean;
}
export interface Profile {
  name:string; username:string; email:string; bio:string;
  reads:number; streak:number; joined:string;
  lastWriteDate?:string; following?:string[];
  likedStories?:string[]; readingList?:string[];
}
export interface RoomMessage {
  id:string; userId:string; userName:string; text:string; sentAt:any;
}
export interface WhisperResult {
  answer:string; count:number; percent:number;
}

// ── CONSTANTS ─────────────────────────────────────────────────────────────────
export const GENRES = ['Romance','Fantasy','Mystery','Sci-Fi','Literary','YA','Horror','Poetry'];
export const DRIFT_STATES = [
  'Something I have never said out loud','A version of me I had forgotten',
  'A feeling I could not name until now','Someone I used to be',
  'Something I am still waiting for','A grief I have not finished yet',
  'A joy I was afraid to want'
];
export const COVERS = ['✍️','📖','🌟','💫','🌸','🎭','🔮','🦋','🕯️','🌙','⭐','🏛️'];
export const GRADIENTS = [
  'linear-gradient(135deg,#e8b4b8,#c97b8a)',
  'linear-gradient(135deg,#a8c5da,#6b8fa8)',
  'linear-gradient(135deg,#c5b8d4,#8b7aab)',
  'linear-gradient(135deg,#b5c9a8,#7a9b6e)',
  'linear-gradient(135deg,#ddc4a0,#b89060)',
  'linear-gradient(135deg,#a8d4d8,#6aabaf)'
];

// ── ROULETTE OPENINGS ─────────────────────────────────────────────────────────
export const ROULETTE_OPENINGS = [
  { id:1, opening:"She arrived at the funeral in the wrong dress and the right state of mind.", genre:"Literary", title:"Wrong Dress", author:"Meera K." },
  { id:2, opening:"The last map ever drawn was of a place no one had ever been — but everyone recognised.", genre:"Fantasy", title:"The Edge", author:"Eiro Black" },
  { id:3, opening:"My mother called at 3am to tell me she had finally remembered my name.", genre:"Romance", title:"Remember", author:"Ananya S." },
  { id:4, opening:"There are twelve ways to disappear. I have tried eleven of them.", genre:"Mystery", title:"Eleven Ways", author:"N. Anand" },
  { id:5, opening:"He built a library out of everything she never said. It had seventeen rooms.", genre:"Romance", title:"The Quiet Library", author:"Priya L." },
  { id:6, opening:"The letter came from a city she had never visited but somehow knew the smell of.", genre:"Literary", title:"The Other City", author:"Ramya D." },
];

// ── CURATED STORIES ───────────────────────────────────────────────────────────
export const CURATED_STORIES: Story[] = [
  { id:'s1', title:'Oka Vennela Raathri', author:'Kavitha Rao', genre:'Romance', lang:'Telugu', cover:'🌙', grad:'linear-gradient(135deg,#c5a8d4,#8b6aab)', desc:'Oka raathri train lo kalisi, okari gurinchi okaru cheppukuntaru. Tella varupu vasthundi. Maatlaadadam aapukuntaaru. Kaani gundelu aapukolevvu.', tags:['romance','train','one night','Telugu'], lateNight:true, chapters:5, reads:'8.4K' },
  { id:'s2', title:'The Library at Closing Time', author:'Meera Krishnan', genre:'Literary', lang:'English', cover:'📚', grad:'linear-gradient(135deg,#d4a8a8,#8b4a4a)', desc:'She inherited a small library from a woman she never met. Inside the last book on the last shelf, she found a letter addressed to her by name.', tags:['mystery','literary','letters'], lateNight:true, chapters:5, reads:'12.3K' },
  { id:'s3', title:'Silence Protocol', author:'Arjun Mehta', genre:'Sci-Fi', lang:'English', cover:'🤫', grad:'linear-gradient(135deg,#a8b4d4,#4a5a8b)', desc:'In 2094, every word spoken costs one credit. A writer falls in love through handwritten notes slipped under doors.', tags:['sci-fi','dystopia','romance'], lateNight:true, chapters:5, reads:'21.8K' },
  { id:'s4', title:'Rendu Gunde Okate Ayathe', author:'Priya Lakshmi', genre:'Romance', lang:'Telugu', cover:'💛', grad:'linear-gradient(135deg,#e8d4a8,#b89060)', desc:'Pativipotha anukunnaru. Kaani jeevanam vaaLLani oka gadi lo pettinattu chesindi. Ippudu vaaLLu choose kovaali.', tags:['romance','reunion','Telugu'], lateNight:false, chapters:5, reads:'34.1K' },
  { id:'s5', title:'When Stars Learn to Fall', author:'Sable Quinn', genre:'YA', lang:'English', cover:'✨', grad:'linear-gradient(135deg,#a8d4d8,#4a8b8f)', desc:'Zara studies stars because they are the only things that stay. Then she meets someone who has never looked up.', tags:['YA','romance','astronomy'], lateNight:false, chapters:5, reads:'47.2K' },
  { id:'s6', title:"The Insomniac's Bookshop", author:'Noor Anand', genre:'Mystery', lang:'English', cover:'🔦', grad:'linear-gradient(135deg,#b5c9a8,#5a7a4a)', desc:'A bookshop in Chennai that only opens between 2am and 5am. The owner never speaks. The books choose their readers.', tags:['mystery','magical realism','Chennai'], lateNight:true, chapters:5, reads:'18.9K' },
  { id:'s7', title:'Thelupu Teeyani Pata', author:'Ramya Devi', genre:'Literary', lang:'Telugu', cover:'🪷', grad:'linear-gradient(135deg,#d4b8a8,#8b5a4a)', desc:'Naanamma oka paata paaDutundi — years gaa. Andulo oka maat artham ippude ardhame avutundi.', tags:['Telugu','family','grandmother','generational'], lateNight:true, chapters:5, reads:'9.8K' },
  { id:'s8', title:'The Architecture of Leaving', author:'Eira Blackwood', genre:'Literary', lang:'English', cover:'🏛️', grad:'linear-gradient(135deg,#c8d4a8,#6a8b4a)', desc:'An architect who designs beautiful homes has never been able to stay in one. She is now building one for herself.', tags:['literary','identity','relationships'], lateNight:true, chapters:5, reads:'15.6K' },
  { id:'s9', title:'This Thing Called Love', author:'Sowmya', genre:'Romance', lang:'English', cover:'🎓', grad:'linear-gradient(135deg,#f5c6d0,#c97b8a)', desc:'Ishika arrived in Hyderabad with too much luggage and no plan. She did not expect to find him in the same classroom. Five years was supposed to be enough time to forget a voice.', tags:['romance','college','Hyderabad','engineering','second chance'], lateNight:false, chapters:1, reads:'New' },
];

// ── CHAPTER CONTENT ───────────────────────────────────────────────────────────
export const STORY_CHAPTERS: Record<string, Record<number, string[]>> = {
  s1: {
    1:["Raathri 11:47 ki train platform meedha aaginattu aagindi. Ame window seat lo kurchundi, outside lights fade avutunnaayi. Seat opposite lo okadu kurche aaDu.","Vaadam leka, 'Mee phone charger daggara undaa?' ani aDigaaDu. Telugu lo. Manchi Telugu. Ame surprised ayyindi.","'Undhi,' ani aame cheppindi. Charger icchindi. Vaaadu thank you cheppaDu. Iddaru silence lo undi poyaaaru.","Platform lights vaellipoyayi. Train motionism start chesindi. Vaaadu cheppindi — 'Meru Hyderabad ki velistunnaaraa?'","'Ledu,' ani aame cheppindi. 'Nenu anni stations daati velaataanu.'"],
    2:["Midnight tarvata vaaadu ame peru aDigaaDu. Ame cheppindi. VaaDu repeet chesaaDu — softga, laanti word ala treat chesaaDu.","VaaDu cheppadu — tanu engineer ani. Bengaluru ki return avutunnaaDu. Oka project complete chesaaDu ani.","Ame aDigindi — 'Emaindi intlo?' VaaDu pause chesaaDu. 'Naa father. He expected too much. I delivered too little.'","Train oka tunnel guunDa velthundi. Darkness lo maatalu matrame untaayi.","Tunnel exit ki, iddaru each other ki smile chesaaru. First time that night."],
    3:["1am ki vaaadu oka story cheppaDu. Ame 2am ki oka rahasyam cheppindi. Iddaru naagindi, nidra raaledhu.","Tella varupu vasthundi. VaaDu vellipoyinattu anipinchindi. Kaani velaadu.","'Meru ikkade nilabadi vellipotaaraa?' ani aame aDigindi.","'Idi naa station kaadu,' ani vaaDu cheppaDu. 'Kaani ikkade digi pothaanam anipistundi.'","Ame silence lo unDipoyyindi."],
    4:["Tella veLLu vastundi. VaaDu coffee teesukoSTE ame kooda vastaadi ani aDigaaDu. VaaLLiddaru dining car ki vellaaru.","Coffee chillga undi. Maatalu warmga undi. Train lo time stand still ayinattu unDi.","Ame cheppindi — 'Nenu ila konni rathrulu train lo gaDipisthaanu. Oka place lo niLabaDeschedam naaku chethagaadu.'","'Naadoo aalagee,' vaaaDu cheppaDu. 'Kaani nenu platform build chesaanu — buildings. NiLabaDesEchutaamu kaaboyi niLabaDesamu.'","Iddaru navvaaru. Coffee cups empty ayayi."],
    5:["Tella vaarupu paDindi. Train station ki 40 minutes unnayi.","VaaDu cheppaDu — 'Meeru number ivvocchaa?'","Ame oka nimisham aalochinchindi. '10 seconds thinking time ki artham — no, right?' vaaDu navivaaDu.","Ame navvindi. Phone teesindi. Number typed chesindi.","Train station ki cheeresindi. Iddaru digi vellaaru. Opposite directions lo. Back choodakuundaa. Kaani gundelu malli choosukovaataaniki try chestaayi."],
  },
  s2: {
    1:["The inheritance notice arrived on a Wednesday. A library — 847 square feet, three thousand books, one cat named Semicolon — left to her by a woman named Leela Krishnaswamy who died at ninety-one.","She had never heard of Leela Krishnaswamy. She googled the name. Nothing useful. A death notice in a Kerala newspaper. An address in Chennai.","Her lawyer said the will was uncontestable. The library was hers. The cat, technically, was optional.","She drove to Chennai the following Saturday. The door was unlocked. The cat sat on the front desk, staring as if she were late.","On the last shelf, behind the last book, there was an envelope. Her name on the front, in handwriting that had known her name before she had given it."],
    2:["The letter was written in three languages. The English parts said: You will have questions. The books will help. Start with the blue ones.","There were eleven blue books. She arranged them on the desk. Semicolon sat on the third one and refused to move.","The first blue book was a diary. A man's hand. Dated 1953. First entry: She opened the library today. I watched from across the street. I did not go in.","The second entry, three days later: I went in. She knew my name before I told her. I do not know how.","She looked up. Outside, across the street, there was a very old man standing very still. He was crying."],
    3:["His name was Mr. Rajan. He was eighty-eight. He had come to stand across the street every Saturday for seventy years.","'She would not see me,' he said. 'Not since 1961. I did something I cannot fix. But I could not stop coming.'","'Why?' she asked.","'Because she never locked the door. In seventy years, she never locked it. I think that was for me. In case I found the courage.'","Semicolon walked over to Mr. Rajan and sat on his shoes."],
    4:["The diary explained everything. A love story interrupted by a family, a war, a decision made in five minutes that took a lifetime to regret.","Leela had kept the library open. For him. For anyone who needed it.","'Did she know you kept coming?' she asked.","He took a long time. 'She left you the library. She left the key. So yes. She knew. She wanted someone to finally open the door for me.'","She looked at the envelope. Her name. Written by a woman she had never met. Waiting eighty years to finish something."],
    5:["She read the rest of the letter that evening, while Semicolon slept on the blue diary.","Leela had written: I don't know who you are. But you found this, which means you were meant to. The library is yours. Let people in. Especially the ones afraid to come through the door.","She looked at three thousand books. At the cat. At the unlocked door.","She called Mr. Rajan. 'Come back tomorrow. I'll make tea. We can read together.'","A long silence. Then: 'She would have liked you.' Which was, she understood, a yes."],
  },
  s3: {
    1:["In 2094, the government introduced the Word Tax. Each spoken word cost one micro-credit. The average person said sixteen thousand words a day. The average person could not afford that anymore.","The rich spoke freely. The middle class curated their sentences. The poor fell into a silence that was first economic, then habitual, then almost peaceful.","Arjun was a writer. He had not spoken in six weeks — saving up for one very specific sentence. He just had not found the right words yet.","He wrote instead. Letters slipped under doors. Notes on café tables. A running conversation with his building, one sticky note at a time.","The woman in 4B had started writing back."],
    2:["He did not know her name. Her notes were signed with a small drawing of a crow.","Her handwriting was precise and slightly angry-looking, as if she disagreed with writing even while doing it.","First note from her: 'You left a note saying I look like I am thinking about something important. This is wildly inappropriate. I was, though.'","He wrote back: 'What were you thinking about?' Slipped it under 4B.","Next morning: 'Whether the silence is making us more honest or less. I cannot decide.'"],
    3:["They wrote for forty days without meeting. The notes got longer, then shorter — more concentrated, like good sentences.","She wrote: 'I used to talk too much. Most of it was filler. Static between things I actually meant.'","He wrote: 'I write for a living but I have been writing filler too. Maybe silence is editing.'","She wrote: 'Or maybe we are romanticising poverty.' He wrote: 'Both can be true.'","Then: 'My name is Zara. In case you wanted to know. The crow is my signature, not my name.'"],
    4:["He saved for three weeks. Spent nothing. Ate cheaply. Walked everywhere.","On a Tuesday, he knocked on 4B. She opened the door. She looked exactly like someone thinking about something important.","He had saved enough credits for one sentence. He had been drafting it for weeks.","He said: 'I think I have been writing these notes to you the way I have always wanted to write — like the words actually matter.' Seven words over budget. Two days of silence. Worth it.","She did not say anything. She stepped back to let him in."],
    5:["On the kitchen table was a notebook — forty days of notes, hers and his, transcribed in order. She had been keeping them.","'I did not want to lose them to paper that degrades,' she said. Three credits. She said it anyway.","He looked at the notebook. Forty days of a conversation the world said they could not afford.","'Some things,' he wrote on a fresh note, not wanting to spend more credits, 'you just have to pay for.'","He drew a small crow next to his name. She laughed. It cost nothing."],
  },
  s4: {
    1:["VaaDiki oka letter raaindi — job offer letter. Different city. Big opportunity.","Table opposite lo aame kurchi undi. VaaDu letter cheppindi. Ame face expression choodandi.","Ame smile chesindi. Kaani eyes smile cheyyaledu. Vaadu adhi gurtupeTTukonaadu.","'Congratulations,' ani aame cheppindi. Genuine ga undhi. Ame adi ananiki try chesindi.","VaaDu letter dooram petTaaDu. Iddaru coffee finish chesaaru. Ela cheppali ani teelusokuntunnaaru."],
    2:["VaaDu packing start chesaaDu. Ame help chesindi. Iddaru maatladaaledu.","Books pack chestuunTe vaaDu okka book teesukoNDi — ame favourite. 'Idi naa daggara undaali,' aame cheppindi.","VaaDu adi ame ki ichaaDu. 'Meeru kuda padataaruga?' ani aDigaaDu.","Ame navvindi — oka sad, real navvu. 'Padaataanu. Kaani naaku nee gurapu osthundi.'","VaaDu aa book teesukoNDi. Iddaru ki second copy order chesaaru — different editions, same story."],
    3:["Airport ki vellaaDu. Ame vachindi. Aanadaniki.","Security line lo vaaDu saamaanu peTTaaDu. Back tirigaaRu. Ame undi — same person who makes him feel like home.","'Nenu raalekapovaatam correct ani feel avutunnava?' ani vaaDu aDigaaDu.","'Avunu,' ani ame cheppindi.","Boarding announce ayyindi. VaaDu vellipoyaaDu. Ame tirigi vellipoyindi. Iddaru okasaari kUDaa back choodalEdu."],
    4:["Six months tarvata. VaaDu calls chestunnaDu. Ame receive chesindi.","Maatalu same ga unnaayi — same humor, same rhythm. Kaani oka gap undi.","'Nenu raavali anipistundi,' vaaDu oka raathri cheppaaRu.","'Nuvvu already raavalani anipistunnava, or simply raavaataaniki ready ga unnava?' ani aDigindi.","VaaDiki difference telusaayindi. 'Both,' ani cheppaDu."],
    5:["VaaDu ticket book chesaaRu. One way.","Platform meedha vaaDu ame ni choodaaDu — same place. She was already there. Waiting.","'Nenu job opportunity miss chesaaanu,' vaaDu cheppaDu.","'Naaku telsu,' ame cheppindi. 'Nuvvu resign chesavaani telushindi naaku three months back. LinkedIn lo choodaanu.'","'Maree eppuDu rammani cheppaledu?' Ame smile chesindi. 'Idi nee decision kaavali. Naa kosamaina raavadam naaku vendakapoyyindi.' Iddaru ikkaDee nilabadi poyaaru."],
  },
  s5: {
    1:["Zara had a rule: never name the stars you study. Name them and you start to care what happens to them.","She had broken this rule exactly once. A star she had tracked since she was twelve. She named it Tuesday — the day she first saw it properly.","Tuesday was dying. She had known for two years. She had not told anyone.","The new boy bumped into her telescope and said, looking up, 'Wow. That is a lot of darkness.'","'It is mostly light,' she said. 'You are just not looking at the right spots.' He looked at her instead. This was, she would realise later, the beginning of the problem."],
    2:["His name was Reo. He had transferred from somewhere warmer and seemed surprised every morning that it was cold.","He found her on the school roof at lunch. She went there to eat alone.","'Can I sit here?' 'The roof?' 'Next to you.' 'They are kind of the same thing.' He sat anyway.","He looked up. She watched him look up. 'Do you know all of them?' 'No. Nobody does.' 'Then what is the point?' 'That is the point.'","He came back the next day. And the next. She stopped trying to make him leave."],
    3:["He asked questions she had stopped asking. Why do stars explode? Do they feel it? Is there a word for missing something you have never had?","She told him about Tuesday. About naming stars against her own rules.","He was quiet for a long time. Then: 'You named it Tuesday because Tuesday is the loneliest day. Nobody looks forward to Tuesdays.'","She had not known that was the reason. 'Maybe that is why I needed to watch it.'","He nodded. This was the first time she felt someone understood the exact shape of what she was carrying."],
    4:["He asked her to show him Tuesday through the telescope. She adjusted the focus. He looked for a long time.","'It does not look like it is dying.' 'It does if you know what you are looking for.'","'What are you looking for?' He was not looking through the telescope anymore.","'Brightness loss. Expansion. Signs that something is getting too big to hold itself together.'","'You are describing a lot of things that are not stars.' She did not answer. The sky was very clear that night."],
    5:["Tuesday went supernova on a Thursday, which she thought was deeply unfair.","She was on the roof when it happened — a brightness that lasted twelve minutes before fading into something new.","Reo had come up without her noticing. He sat next to her and watched.","When it was over she said: 'I am going to miss it.' He said: 'You named it. You watched it. You will write about it. That is more than most things get.'","She looked at him. The sky was very bright where Tuesday had been. 'Yeah,' she said. 'I guess it is.'"],
  },
  s6: {
    1:["The bookshop opens at 2am. It closes at 5am. This has been true for forty years.","She found it because she could not sleep and had walked too far and the light was on. The door opened before she touched it.","Inside: floor-to-ceiling shelves, a cat asleep on the register, and a man who did not speak. He pointed to the shelves and stepped back.","Her hands found a book and would not let go. She bought it. It was exactly right.","She came back the next night. And the next. The man never spoke. He always knew which book."],
    2:["She asked his name on the fourth night. He wrote it on a notepad: Solomon.","She asked how he knew which book. He pointed to her, then his eyes, then the shelves, then shrugged.","She began bringing people. Her sister, grieving. Her friend who had lost something he could not name. A stranger who looked hollow.","Solomon found a book for each of them. None left empty-handed. None could explain what had happened.","She started telling people. Quietly. Only the right ones."],
    3:["On the thirty-seventh night she arrived to find the shop dark. She panicked. Knocked. Called out. Nothing.","Then a light — from the back. Solomon was sitting at a table. Books around him. Looking at one book and not opening it.","She sat across from him. He slid the book to her. No title. No author.","She opened it. First line: There are things that cannot be sold, only given. And there are people who spend a lifetime deciding what those things are.","She read. The cat came and sat on her feet."],
    4:["The book was about the shop. About Solomon. A biography written by everyone who had ever come in at 2am and left with something they needed.","She read through the night. The last chapter was blank.","Solomon pointed to the blank pages. Then to her. 'You want me to write the ending?'","He shook his head. He pointed to the door, then the shelves, then his chest. Then he stood up slowly, walked to the back, and did not come out.","She waited until 5am. He did not return."],
    5:["The cat woke up, stretched, and sat on the register.","She looked at the shelves. At the books that knew their readers. At the unlocked door. At the blank last chapter.","She thought about what it means to keep a light on for people who cannot sleep.","She flipped the sign from CLOSED to OPEN. It was 5:04am. She sat behind the register.","The first customer arrived at 5:09am — a young woman who looked like she had been walking too long. The right book was obvious immediately."],
  },
  s7: {
    1:["Naanamma oka paata paaDuthundi — every day, evening ki, kitchen lo. Ame voice lo notes vinapadataayi kaani lyrics vinapadataayi.","Naaku Telugu sariggaa raadu. English lo think chesthaanu. Kaani aa paata vinapadutundi — body ki artham avuthundi, brain ki kaadu.","Naanamma cheppindi — 'Idi nee tatha paaDe paata. Vaadu naaku nerpinchaDu. Nenu nee amma ki nerpiNchaaRu.'","'Emaindi aa paatalo?' ani naanu aDigaanu.","Naanamma oka nimisham aagindi. 'Anni untaayi. Anni emi levu.' Malli paaDaadaniki start chesindi."],
    2:["Nenu aa lyrics raayyaataaniki try chesaanu. Naanamma ki vinapiNchaaRu.","She corrected two words without looking up from cooking. Both corrections were emotional, not grammatical.","'Oka word vaaDisthe lekha anDi — account ledger. Aa paata lo use chesthe — the thing you cannot stop counting, even when you have already lost count.'","Nenu gurtupeTTukoNDi.","'Nee taatha oka debt lo undi aa paataki. Emi debt ani aDigaanu. Vaadu cheppadaniki refuse chesaaDu. Song paaDaaDu.'"],
    3:["Naanamma old photo album chupinchindi. Naa tatha young ga unnaaDu — naaku similar ga. Almost uncomfortable similar.","Okka photo lo aa tatha oka woman tho unnaDu. Naanamma kaadu.","'Adi evaraa?' naanu aDigaanu.","Naanamma album close chesindi. 'Adi oka paata,' ame cheppindi.","Naaku artham kaaledu. Kaani kaadu ani kooda cheppanu."],
    4:["Naanu paata lyrics translate chesaanu — Telugu nundi English ki. Meaning by meaning, not word by word.","Adi oka love story anipinchindi. Oka specific love story — oka person, oka place, oka mistake.","Naanamma ki chupinchaaRu. She read without expression. Then: 'You got the love part right. You missed the loss part.'","'Emi miss chesaanu?'","'That the love and the loss are the same thing in this song. That is why your great-grandfather could not stop singing it.'"],
    5:["Ame naaku aa paata full story cheppindi — ee raathranta. First time.","Idi complicated love story. Tata adi debt ani cheppaaDu — because some love stories, you carry. Not as burden but as responsibility. To remember them fully.","Naanamma tana paata paaDaindi oka final time, full version, full voice.","Nenu aa paata phone lo record chesaanu. Ame ki permission aDigaanu. 'Ledu,' ame cheppindi. 'Nee memory lo record chesuko. Aa difference telusu.'","Nenu close chesaanu phone. Vinaaanu. Aa paata inkekkaDo naaku vinnaTTu feel avuthundi — oka tatha nunchi oka tatha ki, maatalu lekunda."],
  },
  s8: {
    1:["She designs homes for people who know exactly what they want. They say: we want it to feel like coming home. She builds it. They stay.","She does not stay anywhere.","Her therapist says it is a pattern. She has heard this before. Her therapist is new — the third one this year.","She left her last place on a Tuesday. No note. Key on the counter. Four months into a lease.","She is now designing a home for a couple who want it to feel permanent. She keeps drawing ceilings higher than they asked for."],
    2:["The last person she left was named Kiran. He was good. Genuinely good — the kind that made her feel worse, not better.","He sent one message ten days after she left: 'I hope wherever you are, the ceiling is high. I know you like high ceilings.'","She read it forty times. She did not reply.","She was in a hotel room with a low ceiling. She moved hotels. She moved cities.","She told herself this was fine."],
    3:["She met his sister at an architecture conference. Name tag. 'Oh,' the sister said. 'You are the one who left the high-ceiling message.'","'He told you.' Not a question.","'He said you design places that feel like homes. He said it like it was sad and impressive at the same time.'","'What did you say?' 'I said maybe she cannot stay because she makes homes for other people. And he said maybe. And then he stopped talking about it.'","She left the conference early."],
    4:["She called Kiran that night. After two months. He answered. Neither spoke for thirty seconds.","'How is the ceiling?' he said finally. 'High. I moved.' 'Of course you did.'","A pause. Not hostile. Familiar.","'I am building something. A house. For me. I do not know if I will stay. But I am building it.'","'Can I see it when it is done?' 'I will let you know when it is done.' Which was not a no."],
    5:["The house took eight months. She made mistakes — structural ones she redid, aesthetic ones she left in on purpose.","There was a window facing the wrong direction for light but the right direction for rain. She kept it.","The day it was finished she stood in the empty house and waited to feel the urge to leave. It did not come immediately.","She texted Kiran an address. Just the address.","He came on a Saturday. She made coffee. They stood in the high-ceilinged kitchen. Outside, it rained through the wrong window and looked completely right. 'I like that you built it,' he said. Which was, she understood, the same thing."],
  },
};

  s9: {
    1:[
      "The first thing Ishika noticed about Hyderabad was that the city did not seem particularly interested in welcoming her. It was too loud for that. The road outside the railway station was already crowded when she stepped out, her suitcase dragging awkwardly behind her, one hand clutching her handbag and the other holding her phone as if it might somehow help her find her way through the traffic.",
      "Autos called out from every direction. Buses groaned past. Cars squeezed into spaces that did not seem large enough for cars. Somewhere nearby, someone was arguing loudly over a fare. Ishika stood there for a few seconds, taking it all in. Hyderabad. Her new city. Her mother had spent the entire journey telling her she would get used to it. Her father had spent it checking the hostel address every half hour. Ishika had spent most of it pretending she wasn't nervous.",
      "The hostel room was smaller than she had imagined and larger than her mother had feared. Two beds, two study tables, two cupboards, one window. That was how Ishika met Meera — not through orientation, not through some carefully arranged introduction, but because two nineteen-year-old girls had brought too much luggage to the same hostel corridor. By evening they had discovered they were both CSE. By dinner they had discovered neither knew where the mess was. By ten that night they were talking as though they had known each other for weeks.",
      "The first week disappeared into introductions, lectures, attendance, practical schedules, and the exhausting business of learning which staircase actually led to which floor. The days settled into a rhythm. Morning rush. Classes. Lunch. More classes. Canteen. Hostel. Calls home. Sleep. Repeat. There were hundreds of students in their year. Ishika knew perhaps twenty names. It was easy to be anonymous in a crowd that large. Until one afternoon, she wasn't.",
      "The professor had dismissed them five minutes early. Someone moved into the narrow space beside her desk. 'Sorry.' Ishika stepped aside automatically. There was something about the voice. Not the words. The voice. She looked up. The boy she had known at fourteen was gone. The person standing in front of her was unmistakably him and, somehow, not him at all. He was taller. His shoulders had broadened. His face had sharpened. He looked at her as though he was trying to place two different images over each other. Then he said her name. 'Ishi?' Her breath caught. She looked at him properly. 'Abhi?' The change in his expression was almost imperceptible. A faint smile appeared. Not the easy smile she had seen on dozens of boys around campus. This one was smaller. Quieter. Almost involuntary. And somewhere down the corridor, she realised that after five years of becoming someone else, one quiet 'Ishi?' had made her feel like she had been waiting for that voice without ever knowing it.",
    ],
  },
export const DEFAULT_CHAPTERS: Record<number,string[]> = {
  1:["This is the beginning of something. The writer has not told you where it is going yet. Neither have they, honestly. That is the best kind of beginning.","Some stories start in the middle of things. This one starts at the edge — the place just before a decision gets made, where everything is still possible.","Pay attention to the details. Writers always hide the important things in details. The colour of the cup. The way someone pauses before answering.","You are here now. In this story. Something is about to change.","Keep reading."],
  2:["The second chapter is where things get complicated. The first chapter makes promises. The second chapter starts to keep them — or break them in interesting ways.","Characters become more themselves here. You see what they are like when things get difficult, which is the only time you ever really know anyone.","Are you noticing the pattern? Look again.","You are getting somewhere.","Keep going."],
  3:["This is the middle. The hardest part to write and the most important part to read.","Everything here is load-bearing. The ending will make sense because of what the middle does — or it will not, and that will also be because of the middle.","Some things are about to become clear. Other things less clear. Both are necessary.","The writer is working hard right now. Can you feel it?","Keep going."],
  4:["You are nearly there. The writer can see the end from here.","This is where the characters have to choose. The story has been building toward a choice.","Everything matters more now. Read slowly.","The writer put something important in this chapter. You will know it when you find it.","Almost."],
  5:["The last chapter. You have come this far, which means this story found something in you.","Endings are not conclusions. Good endings are the last note of something that keeps ringing. You carry them with you.","How does this one land?","If you are feeling something right now — that is the story working. That is it doing what it came to do.","Thank you for reading. Go tell the writer."],
};
